# Generated by Django 4.2.6 on 2023-11-01 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Caña_pesca',
            new_name='Caña_de_pescar',
        ),
    ]
