# Generated by Django 4.2.6 on 2023-11-18 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_reels_señuelo'),
    ]

    operations = [
        migrations.AddField(
            model_name='caña_de_pescar',
            name='fecha_creacion',
            field=models.DateField(null=True),
        ),
    ]
