# Generated by Django 4.2.6 on 2023-11-19 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0008_alter_caña_de_pescar_fecha_creacion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Caña_de_pescar',
            new_name='CañaDePescar',
        ),
    ]
